### ISSUE TITLE
Model classes updated

### ISSUE THREAD

**Issue by mattpitkin** [BayesFlare/bayesflare#1]
In the models branch there have been enhancements so that there is now a generic Model class. The individual signal models (e.g. the Flare model) now inherit the characteristics of the Model class.

In this update the methods within the classes that define the model function now only take in dictionaries of parameter values, with the dictionaries having to contain parameters required for the given model.

A new model class for a Step function is also included.

This has been tested and the plot_lightcurve script works correctly, but other tests should be performed (i.e. do the analysis scripts, and threshold/efficiency scripts still work). It should then be merged with the master branch and a new release be created.

**Comment by mattpitkin** [comment]
@transientlunatic - would you be happy with me merging this patch into master? It may create a fair few conflicts with your light curve generalisation branch.

**Comment by transientlunatic** [comment]
Looks fine to me; I'll resolve the merge conflicts whenever the lightcurve work's ready to fully incorporate into master.
:+1:
