### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by arizzuto** [BayesFlare/bayesflare#7]
Hello, 

when I try to import the package I get the following error, I'm running it on a Mac:

> > > import bayesflare
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/aaron/anaconda/lib/python2.7/site-packages/bayesflare/**init**.py", line 36, in <module>
> > >     from .models import Model, Flare, Transit, Expdecay, Impulse, Gaussian, Step, ModelCurve
> > >   File "/Users/aaron/anaconda/lib/python2.7/site-packages/bayesflare/models/**init**.py", line 5, in <module>
> > >     from .model import Model, Flare, Transit, Expdecay, Impulse, Gaussian, Step, ModelCurve
> > >   File "/Users/aaron/anaconda/lib/python2.7/site-packages/bayesflare/models/model.py", line 4, in <module>
> > >     from ..stats.general import logminus
> > >   File "/Users/aaron/anaconda/lib/python2.7/site-packages/bayesflare/stats/**init**.py", line 11, in <module>
> > >     from .general import *
> > > ImportError: No module named general

**Comment by transientlunatic** [comment]
Hi,
Can I check if you installed from master, or from one of the releases?

**Comment by arizzuto** [comment]
Hello,
I tried it with the latest release, and got the same result with a pip install.

**Comment by transientlunatic** [comment]
Okay, so I think this problem has been fixed on master, and just hasn't made its way into a release. 

Can you try installing from master and see if that works? I think this is a problem with Cython on Mac.

**Comment by arizzuto** [comment]
I tried with a clone of master and got the same result. Note that to get "python setup.py install"
to work I had to add the following line to the setup.py script inside the setup() call:

include_dirs=[numpy.get_include()]

**Comment by mattpitkin** [comment]
I think (after all this time) I've solved the issue with #8. @arizzuto - I'm not sure if you're at all interested in this anymore seeing as we've taken so long to solve it, but if you want to give the fix a try please let us know if it works for you.

**Comment by mattpitkin** [comment]
This issue should hopefully be fixed with #8, which has now been merged into master.
